id: A0CF9354F
title: Three Prayers from the Earth Pig Year
type: translation
pechas:
- I66B5D66A
- I43449036
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:18.123558
  last_modified_at: 2023-01-04 13:10:18.123562
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I66B5D66A/FD18: CFB8
  I43449036/9FBF: CFB8
